# Jaeger All-in-One Deployment
# 
# Deploys Jaeger for distributed tracing in development mode.
# For production, use Jaeger Operator with Elasticsearch backend.
#
# Components:
# - Jaeger agent: Receives traces from applications
# - Jaeger collector: Processes and stores traces
# - Jaeger query: Provides API for trace retrieval
# - Jaeger UI: Web interface for trace visualization
#
# Access:
#   kubectl port-forward -n monitoring svc/jaeger 16686:16686
#   http://localhost:16686

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - port: 5775
      protocol: UDP
      name: zipkin-compact
      targetPort: 5775
    - port: 6831
      protocol: UDP
      name: jaeger-compact
      targetPort: 6831
    - port: 6832
      protocol: UDP
      name: jaeger-binary
      targetPort: 6832
    - port: 5778
      protocol: TCP
      name: config-rest
      targetPort: 5778
    - port: 16686
      protocol: TCP
      name: ui
      targetPort: 16686
    - port: 14268
      protocol: TCP
      name: collector
      targetPort: 14268
    - port: 14250
      protocol: TCP
      name: grpc
      targetPort: 14250
  selector:
    app: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.52
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
            - name: SPAN_STORAGE_TYPE
              value: "memory"
            # For production: use elasticsearch
            # - name: SPAN_STORAGE_TYPE
            #   value: "elasticsearch"
            # - name: ES_SERVER_URLS
            #   value: "http://elasticsearch:9200"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 10
            periodSeconds: 5
