---
# Topic: telemetry
# High-volume device telemetry (1 message/device/minute)
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: telemetry
  namespace: kafka
  labels:
    strimzi.io/cluster: iot-ops-kafka
    app.kubernetes.io/part-of: iot-ops-copilot
spec:
  partitions: 100
  replicas: 3
  config:
    retention.ms: 604800000  # 7 days
    compression.type: gzip
    min.insync.replicas: 2
    segment.ms: 3600000  # 1 hour
    cleanup.policy: delete

---
# Topic: events
# Medium-volume state changes, errors, threshold breaches
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: events
  namespace: kafka
  labels:
    strimzi.io/cluster: iot-ops-kafka
    app.kubernetes.io/part-of: iot-ops-copilot
spec:
  partitions: 50
  replicas: 3
  config:
    retention.ms: 2592000000  # 30 days
    compression.type: gzip
    min.insync.replicas: 2
    segment.ms: 86400000  # 24 hours
    cleanup.policy: delete

---
# Topic: alerts
# Low-volume actionable alerts
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: alerts
  namespace: kafka
  labels:
    strimzi.io/cluster: iot-ops-kafka
    app.kubernetes.io/part-of: iot-ops-copilot
spec:
  partitions: 20
  replicas: 3
  config:
    retention.ms: 7776000000  # 90 days
    compression.type: gzip
    min.insync.replicas: 2
    segment.ms: 86400000  # 24 hours
    cleanup.policy: delete

---
# Topic: heartbeat
# Device heartbeat messages (every 60 seconds)
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: heartbeat
  namespace: kafka
  labels:
    strimzi.io/cluster: iot-ops-kafka
    app.kubernetes.io/part-of: iot-ops-copilot
spec:
  partitions: 20
  replicas: 3
  config:
    retention.ms: 2592000000  # 30 days
    compression.type: gzip
    min.insync.replicas: 2
    segment.ms: 3600000  # 1 hour
    cleanup.policy: delete
