# Kafka Cluster (KRaft Mode - No ZooKeeper)
# Strimzi 0.46+ only supports KRaft mode
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  namespace: kafka
  labels:
    strimzi.io/cluster: iot-ops-kafka
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: ephemeral
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: kafka
  labels:
    strimzi.io/cluster: iot-ops-kafka
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: ephemeral
    # For production:
    # type: persistent-claim
    # size: 100Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi

---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: iot-ops-kafka
  namespace: kafka
  annotations:
    strim.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.1.1  # Latest supported by Strimzi 0.46+
    
    # Metadata config (KRaft replaces ZooKeeper)
    metadataVersion: 3.8-IV0
    
    # Listeners
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    
    # Broker configuration
    config:
      # Topic defaults
      num.partitions: 100
      default.replication.factor: 3
      min.insync.replicas: 2
      
      # Disable auto topic creation
      auto.create.topics.enable: false
      
      # Performance
      compression.type: gzip
      log.retention.hours: 168  # 7 days
      log.segment.bytes: 1073741824  # 1GB
      
      # Replication
      replica.lag.time.max.ms: 30000
      replica.fetch.max.bytes: 1048576
      
      # Consumer groups
      offsets.retention.minutes: 10080  # 7 days
      
      # Transaction settings
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    
    # Metrics (Prometheus JMX Exporter)
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  
  # Entity Operator (Topic and User operators)
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
    
    userOperator:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

---
# ConfigMap for Kafka metrics (Prometheus JMX Exporter)
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics
  namespace: kafka
  labels:
    app: strimzi
data:
  kafka-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
      # Broker metrics
      - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
        labels:
          clientId: "$3"
          topic: "$4"
          partition: "$5"
      - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
        labels:
          clientId: "$3"
          broker: "$4:$5"
      - pattern: kafka.server<type=(.+), name=(.+)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
      
      # Network metrics
      - pattern: kafka.network<type=RequestMetrics, name=RequestsPerSec, request=(.+)><>Count
        name: kafka_network_requestspersec
        type: COUNTER
        labels:
          request: "$1"
      
      # Log metrics
      - pattern: kafka.log<type=LogFlushStats, name=LogFlushRateAndTimeMs><>Count
        name: kafka_log_flushes_total
        type: COUNTER
